### ISSUE TITLE
Question about Signature generation

### ISSUE THREAD

**Issue by AcorpBG** [pogodevorg/pgoapi#82]
Hello I'm wondering as of right now does the api use list of viable device information to generate the signature or it is static for example everytime the same firmware/board etc. 
Can this information be passed to the api on signature initialization? 
Is there plans projects that are doing that.

**Comment by ProLoDs** [comment]
I would be intrested too

**Comment by peter-bonanni** [comment]
Interested in this as well and willing to work on it.

**Comment by cheesynoob** [comment]
The signature uses the same device info every time right now, If you want to use different information I would recommend setting it manually in any applications using the API, just keep it constant for each account because the signature needs to be recalculated each time you make a request (Due to U24) So if you have it pick random information each time it would appear as if you were changing devices with every request which is not ideal.

**Comment by AcorpBG** [comment]
@cheesynoob 
Looking at the current rpc_api 
`_build_main_request(self, subrequests, player_position=None)`
It takes only player_position as parameters and takes the defaults from _b on the signature_pb2

I added this for a test to rpc_api 
`                sig.DeviceInfo.device_brand = "samsung" `
`                sig.DeviceInfo.device_model = "GT-I9100"`
`                sig.unk22 = os.urandom(32)`
`                sig.timestamp = get_time(ms=True)`

It seems to work but I'm not sure if I did that correctly

**Comment by TalSkverer** [comment]
@AcorpBG You did this correctly.
Regarding the problem at hand, we're looking at implementing a bigger feature; 'realistic' sensor-like behavior to fill the plaintext fields inside the Signature proto.
Even if we implement such a thing, it raises the question of how close we want to simulate an actual device; for instance - we found out that using a real Android device creates an unknown5 with real satellite information which will be very difficult to generate.

**Comment by leftie1** [comment]
@cheesynoob What device info is sent at the moment?
